pull_request_rules:
  - name: renovate
    conditions:
      - author=renovate[bot]
      - "#status-failure=0"
      - "#label=0"
      - "status-success=WIP"
    actions:
      label:
        add: ["auto-merge"]

  - name: imgbot
    conditions:
      - author=imgbot[bot]
      - "#status-failure=0"
      - "#label=0"
      - "status-success=WIP"
    actions:
      label:
        add: ["auto-merge"]

  - name: stop on label
    conditions:
      - label=auto-merge
      - label=manual-merge
    actions:
      label:
        remove: ["auto-merge"]

  - name: auto-merge
    conditions:
      - label=auto-merge
      - "status-success=ci/circleci: test"
      - "#changes-requested-reviews-by=0"
      - "#status-neutral=0"
      - "#status-failure=0"
    actions:
      merge:
        method: squash
        strict: smart
      delete_head_branch: {}
