version: 2

defaults: &defaults

jobs:
  test:
    context: docker-hub-credentials
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo apt-get update
            sudo pip3 install vyper==0.1.0b13
            # For custom Vyper builds
            # cd ..
            # git clone https://github.com/ethereum/vyper.git
            # cd vyper
            # sudo pip3 install . 
            # export PATH=$PATH:$PWD/bin

      # Cache disabled as `npm i` occasionally fails on dependancies which use websocket
      - run: npm i

      - run: npm run compile
      - run: npm run test
      - run: npm run lintNoFix

workflows:
  version: 2
  build:
    jobs:
      - test
